# Generated by Django 4.0.2 on 2022-02-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='description',
            new_name='type',
        ),
    ]
